config/routes.rb
Rails.application.routes.draw do

  root 'program#index'

  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  match ':controller(/:action(/:id))(.:format)' , via: [:post, :get]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
  
end

app/controllers/program_controller.rb
class ProgramController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/program_helper.rb
module ProgramHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <p id="copyright">&copy; rpastie.com / Jose M. Tobar</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">

  <div class="collapse navbar-collapse">
    <button class="navbar-toggle" data-target="#navbar-collapsible" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <%= link_to "rPastie", root_path, class: "navbar-brand"%>

    <form class="navbar-form col-md-6">
      <div class="form-group" style="display:inline;">
        <div class="input-group">
          <input class="form-control" placeholder="Search" type="text">
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-search"></span>
          </span>
        </div>
      </div>
    </form>

    <ui class="nav navbar-nav navbar-right">
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>

</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>rpaste</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>

<body>
  <%= render 'layouts/header'%>
  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? " success " : "danger " %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
      <% end %>
    <% end %>
<%= yield %>

<%= render 'layouts/footer' %>
  </div>

</body>

</html>

app/views/pages/about.html.erb
<h1>About: rPastie</h1>
<article>
  <p>
  We are a simple pastebin alternative written completely in Ruby, utilizing the Rails framework.
  If you'd like to suggest features or notice any glitches please go to our <%= link_to 'github page', 'https://github.com/ilovemysillybanana/rpaste' %>
  <br>
  We are currently looking for a designer, however, we do not possess a 'designer-having'-budget,
  but if you feel like contributing to the cause and adding us to your portfolio, go head! :)
  <p>
</article>

app/views/pages/contact.html.erb
<%= form_tag({controller: "pages_controller", action: "contact"}, method: "get", class: "form-group")%>
<div class="form-group">
  <%= label_tag(:q, "Name: ")%>
  <%= text_field_tag(:q,'', :placeholder => 'John Smith' ,class: "form-control")%>
  <br>
  <%= label_tag(:q, "Email: ")%>
  <%= text_field_tag(:q,'', :placeholder => 'johnsmith@example.com', class: "form-control")%>
  <br>
  <%= label_tag(:q, "Subject: ")%>
  <%= text_field_tag(:q,'', :placeholder => 'Advertisement Opportunity', class: "form-control")%>
  <br>
  <%= label_tag(:q, "Phone: ")%>
  <%= text_field_tag(:q,'', :placeholder => '15554443333', class: "form-control")%>
  <br>
  <%= label_tag(:q, "Message: ")%>
  <%= text_area_tag(:q,'', :placeholder => 'I would like to talk to you please give me a call.', class: "form-control")%>
  <br>
  <%= submit_tag("Submit", class: "btn btn-primary")%>
</div>
<end>

app/views/program/index.html.erb
<h1>Program#index</h1>
<p>Find me in app/views/program/index.html.erb</p>

app/views/program/show.html.erb
<h1>Program#show</h1>
<p>Find me in app/views/program/show.html.erb</p>